// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQs3dv9jEqw_daTZ51A0_ly1p7O7I3WtI',
    appId: '1:355241701297:android:fe8a1766719d3c49dad790',
    messagingSenderId: '355241701297',
    projectId: 'research-project-25ec0',
    databaseURL: 'https://research-project-25ec0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'research-project-25ec0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Mz_bPOpOiBH32Tq5SqY2MnkyUis9qg4',
    appId: '1:355241701297:ios:75e3134cf56bfa31dad790',
    messagingSenderId: '355241701297',
    projectId: 'research-project-25ec0',
    databaseURL: 'https://research-project-25ec0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'research-project-25ec0.appspot.com',
    iosBundleId: 'com.example.researchproject',
  );
}
